// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef ACTRES_REQ_STATUS_H
#define ACTRES_REQ_STATUS_H

namespace vdis
{
    typedef enum
    {
        ACTRES_REQ_STATUS_ACTRES_REQ_OTHER = 0,
        ACTRES_REQ_STATUS_ACTRES_REQ_PENDING = 1,
        ACTRES_REQ_STATUS_ACTRES_REQ_EXECUTING = 2,
        ACTRES_REQ_STATUS_ACTRES_REQ_PARTIALLY_COMPLETE = 3,
        ACTRES_REQ_STATUS_ACTRES_REQ_COMPLETE = 4,
        ACTRES_REQ_STATUS_ACTRES_REQ_REQUEST_REJECTED = 5,
        ACTRES_REQ_STATUS_ACTRES_REQ_RETRANSMIT_REQUEST_NOW = 6,
        ACTRES_REQ_STATUS_ACTRES_REQ_RETRANSMIT_REQUEST_LATER = 7,
        ACTRES_REQ_STATUS_ACTRES_REQ_INVALREQ_TIME_PARAMETERS = 8,
        ACTRES_REQ_STATUS_ACTRES_REQ_SIM_TIME_EXCEEDED = 9,
        ACTRES_REQ_STATUS_ACTRES_REQ_REQUEST_DONE = 10,
        ACTRES_REQ_STATUS_ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_1 = 100,
        ACTRES_REQ_STATUS_ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_2 = 101,
        ACTRES_REQ_STATUS_ACTRES_REQ_JOIN_EXERCISE_REQ_REJECTED = 201,
        ACTRES_REQ_STATUS_END
    } actres_req_status_e;
}

#endif
