// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef DESIG_SYSTEM_NAME_H
#define DESIG_SYSTEM_NAME_H

namespace vdis
{
    typedef enum
    {
        DESIG_SYSTEM_NAME_DES_SYS_NAME_NO_STATEMENT = 0,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_16 = 1,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_22A = 2,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_22B = 3,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_22C = 4,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_22D = 5,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_28_LITENING = 6,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAQ_7 = 7,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_35V_PAVE_PENNY = 8,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_37 = 9,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_38 = 10,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_44 = 11,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_49 = 12,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_51 = 13,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_AAS_53 = 14,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_GVS_5 = 15,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_TVQ_2 = 16,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_DAK_1_SAGE_GLOSS = 17,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_DHY_307 = 18,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_SACLOS = 19,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_TPDK_1 = 20,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_1D15 = 21,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_1D20 = 22,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_1D22 = 23,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_IZLID_428P_W = 24,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AIM_1_SLX_SUPER_LONG_RANGE_IR_AIMING_LASER = 25,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AIM_1_SLR_SUPER_LONG_RANGE_IR_AIMING_LASER = 26,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_AN_PEQ_2A_IR_AIMING_LASER = 27,
        DESIG_SYSTEM_NAME_DES_SYS_NAME_ACP_2A_AIR_COMMANDER_POINTER_IR_AIMING_LASER = 28,
        DESIG_SYSTEM_NAME_END
    } desig_system_name_e;
}

#endif
