// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef HEADGAZWEAPAIM_TYPE_H
#define HEADGAZWEAPAIM_TYPE_H

namespace vdis
{
    typedef enum
    {
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_NOT_SPECIFIED = 0,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_UP = 1,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_DOWN = 2,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_LEFT = 3,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_RIGHT = 4,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_FORWARD = 5,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_BACKWARD = 6,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_SPECIFIED_GLOBAL_LOCATION = 7,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_SPECIFIED_ORIENTATION_VECTOR = 8,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_TRACKED_CENTER = 9,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_TRACKED_STATION = 10,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_OUT_STATION_NOT_TRACKED = 11,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_OUT_STATION_TRACKED_CENTER = 12,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_OUT_STATION_TRACKED_STATION = 13,
        HEADGAZWEAPAIM_TYPE_HGWA_TYPE_STOWED_EYES_CLOSED = 14,
        HEADGAZWEAPAIM_TYPE_END
    } headgazweapaim_type_e;
}

#endif
