// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef IFF_SYSTEM_TYPE_H
#define IFF_SYSTEM_TYPE_H

namespace vdis
{
    typedef enum
    {
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_NOT_USED = 0,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_X_XII_ATCRBS_TRANS = 1,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_X_XII_ATCRBS_INT = 2,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_SOVIET_TRANS = 3,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_SOVIET_INT = 4,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_RRB_TRANS = 5,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_XIIA_INT = 6,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MODE_5_INT = 7,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MODE_S_INT = 8,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_XIIA_TRANS = 9,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MODE_5_TRANS = 10,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MODE_S_TRANS = 11,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_XIIA_CIT = 12,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_MARK_XII_CIT = 13,
        IFF_SYSTEM_TYPE_IFF_SYS_TYPE_TCAS_ACAS_TRANSCEIVER = 14,
        IFF_SYSTEM_TYPE_END
    } iff_system_type_e;
}

#endif
