// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef IFF_SYSTEM_NAME_H
#define IFF_SYSTEM_NAME_H

namespace vdis
{
    typedef enum
    {
        IFF_SYSTEM_NAME_IFF_SYS_NAME_OTHER = 0,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_X = 1,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_XII = 2,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_ATCRBS = 3,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_SOVIET = 4,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MODE_S = 5,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_X_XII_ATCRBS = 6,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_X_XII_ATCRBS_MODE_S = 7,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_ARI_5954 = 8,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_ARI_5983 = 9,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_RRB = 10,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_XIIA = 11,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MODE_5 = 12,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_XIIA_CIT = 13,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_XII_CIT = 14,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_TCAS_I_ACAS_I_TRANSCEIVER = 15,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_TCAS_II_ACAS_II_TRANSCEIVER = 16,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_X_A = 17,
        IFF_SYSTEM_NAME_IFF_SYS_NAME_MARK_X_SIF = 18,
        IFF_SYSTEM_NAME_END
    } iff_system_name_e;
}

#endif
