// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef MESSAGE_FORMAT_ENUM_H
#define MESSAGE_FORMAT_ENUM_H

namespace vdis
{
    typedef enum
    {
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_LINK_16 = 0,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_BINARY = 1,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_VMF = 2,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_NITFS = 3,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_FWD_MSG = 4,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_USMTF = 5,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_DOI_103 = 6,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_XML_MTF = 7,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_47001C_XML_VMF = 8,
        MESSAGE_FORMAT_ENUM_MESSAGE_FORMAT_AFAPD = 16,
        MESSAGE_FORMAT_ENUM_END
    } message_format_enum_e;
}

#endif
