// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef PL_PAINT_SCHEME_H
#define PL_PAINT_SCHEME_H

namespace vdis
{
    typedef enum
    {
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_DEFAULT = 0,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_SOLID = 1,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_TWO_TONE_TOP_BOTTOM = 2,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_TWO_TONE_BODY_BED = 3,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_TWO_TONE_BODY_TRIM = 4,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_DESERT = 5,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_JUNGLE = 6,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_SNOW = 7,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_GRAVEL = 8,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_PAVEMENT = 9,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_SAND = 10,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CAMO_FOREST = 11,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_NATURAL_WOOD = 12,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_CLEAR = 13,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_UN = 14,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_TAXI = 15,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_NEWS = 16,
        PL_PAINT_SCHEME_PLAT_PAINT_SCHEME_JINGLE = 17,
        PL_PAINT_SCHEME_END
    } pl_paint_scheme_e;
}

#endif
