// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef PLAT_CAT_LAND_H
#define PLAT_CAT_LAND_H

namespace vdis
{
    typedef enum
    {
        PLAT_CAT_LAND_OTH = 0,
        PLAT_CAT_LAND_TANK = 1,
        PLAT_CAT_LAND_AFV = 2,
        PLAT_CAT_LAND_AUV = 3,
        PLAT_CAT_LAND_SPA = 4,
        PLAT_CAT_LAND_TOW = 5,
        PLAT_CAT_LAND_SWUV = 6,
        PLAT_CAT_LAND_LWUV = 7,
        PLAT_CAT_LAND_STUV = 8,
        PLAT_CAT_LAND_LTUV = 9,
        PLAT_CAT_LAND_MORT = 10,
        PLAT_CAT_LAND_PLOW = 11,
        PLAT_CAT_LAND_RAKE = 12,
        PLAT_CAT_LAND_ROLL = 13,
        PLAT_CAT_LAND_CARGO = 14,
        PLAT_CAT_LAND_FUEL = 15,
        PLAT_CAT_LAND_GEN = 16,
        PLAT_CAT_LAND_WATER = 17,
        PLAT_CAT_LAND_ENG = 18,
        PLAT_CAT_LAND_HET = 19,
        PLAT_CAT_LAND_MET = 20,
        PLAT_CAT_LAND_LIMB = 21,
        PLAT_CAT_LAND_CDEC = 22,
        PLAT_CAT_LAND_WARN = 23,
        PLAT_CAT_LAND_TREN = 24,
        PLAT_CAT_LAND_TRCAR = 25,
        PLAT_CAT_LAND_TRCAB = 26,
        PLAT_CAT_LAND_CIV = 27,
        PLAT_CAT_LAND_ADUE = 28,
        PLAT_CAT_LAND_C3I = 29,
        PLAT_CAT_LAND_OPS = 30,
        PLAT_CAT_LAND_INT = 31,
        PLAT_CAT_LAND_SURV = 32,
        PLAT_CAT_LAND_COMU = 33,
        PLAT_CAT_LAND_COM = 34,
        PLAT_CAT_LAND_C4I = 35,
        PLAT_CAT_LAND_CTRL = 36,
        PLAT_CAT_LAND_FIRE = 37,
        PLAT_CAT_LAND_MDEF = 38,
        PLAT_CAT_LAND_FCOM = 39,
        PLAT_CAT_LAND_OBS = 40,
        PLAT_CAT_LAND_GWV = 41,
        PLAT_CAT_LAND_MOTORCYCLE = 80,
        PLAT_CAT_LAND_CAR_SEDAN = 81,
        PLAT_CAT_LAND_BUS = 82,
        PLAT_CAT_LAND_SINGLE_UNIT_CARGO_TRUCK = 83,
        PLAT_CAT_LAND_SINGLE_UNIT_UTILITY_EMERGENCY_TRUCK = 84,
        PLAT_CAT_LAND_MULTIPLE_UNIT_CARGO_TRUCK = 85,
        PLAT_CAT_LAND_MULTIPLE_UNIT_UTILITY_EMERGENCY_TRUCK = 86,
        PLAT_CAT_LAND_CONSTRUCTION_SPECIALTY_VEHICLE = 87,
        PLAT_CAT_LAND_FARM_SPECIALTY_VEHICLE = 88,
        PLAT_CAT_LAND_TRAILER = 89,
        PLAT_CAT_LAND_CAR_COUPE = 90,
        PLAT_CAT_LAND_CAR_3_DOOR_HATCHBACK = 91,
        PLAT_CAT_LAND_CAR_5_DOOR_HATCHBACK = 92,
        PLAT_CAT_LAND_RECREATIONAL = 93,
        PLAT_CAT_LAND_NON_MOTORIZED = 94,
        PLAT_CAT_LAND_TRAINS = 95,
        PLAT_CAT_LAND_UTILITY_EMERGENCY_CAR = 96,
        PLAT_CAT_LAND_END
    } plat_cat_land_e;
}

#endif
