// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef RADIO_TYPE_CAT_H
#define RADIO_TYPE_CAT_H

namespace vdis
{
    typedef enum
    {
        RADIO_TYPE_CAT_RT_CAT_OTHER = 0,
        RADIO_TYPE_CAT_RT_CAT_VOICE_TRANS_REC = 1,
        RADIO_TYPE_CAT_RT_CAT_DATA_LINK_TRANS_REC = 2,
        RADIO_TYPE_CAT_RT_CAT_VOICE_AND_DATA_LINK_TRANS_REC = 3,
        RADIO_TYPE_CAT_RT_CAT_ILS_GLIDESLOPE_TRANS = 4,
        RADIO_TYPE_CAT_RT_CAT_ILS_LOCALIZER_TRANS = 5,
        RADIO_TYPE_CAT_RT_CAT_ILS_OUTER_MARKER_BEACON = 6,
        RADIO_TYPE_CAT_RT_CAT_ILS_MIDDLE_MARKER_BEACON = 7,
        RADIO_TYPE_CAT_RT_CAT_ILS_INNER_MARKER_BEACON = 8,
        RADIO_TYPE_CAT_RT_CAT_ILS_REC_PLATFORM_RADIO = 9,
        RADIO_TYPE_CAT_RT_CAT_TACAN_TRANS_GFE = 10,
        RADIO_TYPE_CAT_RT_CAT_TACAN_REC_MPE = 11,
        RADIO_TYPE_CAT_RT_CAT_TACAN_TRANS_REC_MPE = 12,
        RADIO_TYPE_CAT_RT_CAT_VOR_TRANS_GFE = 13,
        RADIO_TYPE_CAT_RT_CAT_VOR_WITH_DME_TRANS_GFE = 14,
        RADIO_TYPE_CAT_RT_CAT_COMBINED_VOR_ILS_REC_MPE = 15,
        RADIO_TYPE_CAT_RT_CAT_COMBINED_VOR_TACAN_TRANS = 16,
        RADIO_TYPE_CAT_RT_CAT_NDB_TRANS = 17,
        RADIO_TYPE_CAT_RT_CAT_NDB_REC = 18,
        RADIO_TYPE_CAT_RT_CAT_NDB_WITH_DME_TRANS = 19,
        RADIO_TYPE_CAT_RT_CAT_DME = 20,
        RADIO_TYPE_CAT_RT_CAT_LINK_11_TERMINAL = 22,
        RADIO_TYPE_CAT_RT_CAT_LINK_11B_TERMINAL = 23,
        RADIO_TYPE_CAT_RT_CAT_EPLRS_SADL_TERMINAL = 24,
        RADIO_TYPE_CAT_RT_CAT_IFDL = 25,
        RADIO_TYPE_CAT_RT_CAT_F35_MADL = 26,
        RADIO_TYPE_CAT_RT_CAT_SINCGARS_TERMINAL = 27,
        RADIO_TYPE_CAT_RT_CAT_L_BAND_SATCOM_TERMINAL = 28,
        RADIO_TYPE_CAT_RT_CAT_IBS_IS_TERMINAL = 29,
        RADIO_TYPE_CAT_RT_CAT_GPS = 30,
        RADIO_TYPE_CAT_END
    } radio_type_cat_e;
}

#endif
