// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef ACTION_SEQ_TYPE_H
#define ACTION_SEQ_TYPE_H

namespace vdb
{
    typedef enum
    {
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_NOT_SPECIFIED = 0,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_STANDING_UP = 1,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_STANDING_UP_HANDS = 2,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_STANDING_UP_KNEES = 3,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_STANDING_UP_ELBOWS = 4,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KIP_UP = 99,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN = 100,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN_FACE_FIRST = 101,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN_BACKWARD = 102,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN_LEFT_SIDE = 103,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN_RIGHT_SIDE = 104,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FALLING_DOWN_CRUMPLING = 105,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KNEELING = 200,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KNEELING_BOTH_OR_REAR_KNEES = 201,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KNEELING_RIGHT_KNEE = 202,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KNEELING_LEFT_KNEE = 203,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_KNEELING_ALL_KNEES = 204,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CROUCHING_BENDING = 205,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CROUCHING_SQUATTING = 206,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING = 300,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_UNHEEDED = 301,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_CAREFUL = 302,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_TIP_TOE = 303,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_BACKWARDS = 304,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_UPSTAIRS = 305,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_DOWNSTAIRS = 306,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_LIMPING = 307,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_DRAGGING_INJURED_LEG = 308,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_DRAGGING_INJURED_RIGHT_LEG = 309,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_WALKING_DRAGGING_INJURED_LEFT_LEG = 310,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING = 400,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING_FULL = 401,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING_JOGGING = 402,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING_BACKWARDS = 403,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING_UPSTAIRS = 404,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RUNNING_DOWNSTAIRS = 405,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CRAWLING = 500,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CRAWLING_HANDS_AND_KNEES = 501,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CRAWLING_ELBOWS = 502,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_CRAWLING_HANDS_DRAGGING_FEET = 503,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_VOMITING = 600,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_VOMITING_HANDS_AND_KNEES = 601,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_VOMITING_BENDING_OVER = 602,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_EATING = 700,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_DRINKING = 750,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_SLEEPING = 800,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_BREATHING = 900,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_BREATHING_HARD = 901,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_BREATHING_SLOW = 902,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_BREATHING_PANTING = 903,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_URINATING = 910,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_DEFECATING = 920,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_MOUNTING_VEHICLE = 1000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_DISMOUNTING_VEHICLE = 2000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_FIRING_PORTABLE_WEAPON = 3000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_THROWING_PORTABLE_WEAPON_OBJECT = 4000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_USING_CARRIED_EQUIPMENT = 5000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_USING_OTHER_EQUIPMENT = 10000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_OPERATING_VEHICLE = 11000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RIDING_LIFEFORM = 12000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_MOUNTING_LIFEFORM = 13000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_DISMOUNTING_LIFEFORM = 14000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RELOADING_PORTABLE_WEAPON = 15000,
        ACTION_SEQ_TYPE_ACTN_SEQ_TYPE_RELOADING_NON_PORTABLE_WEAPON = 17000,
        ACTION_SEQ_TYPE_END
    } action_seq_type_e;
}

#endif
