// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef ARTICULATED_PARTS_METRIC_H
#define ARTICULATED_PARTS_METRIC_H

namespace vdb
{
    typedef enum
    {
        ARTICULATED_PARTS_METRIC_EMPTY = 0,
        ARTICULATED_PARTS_METRIC_POSITION = 1,
        ARTICULATED_PARTS_METRIC_POSITION_RATE = 2,
        ARTICULATED_PARTS_METRIC_EXTENSION = 3,
        ARTICULATED_PARTS_METRIC_EXTENSION_RATE = 4,
        ARTICULATED_PARTS_METRIC_X = 5,
        ARTICULATED_PARTS_METRIC_X_RAT = 6,
        ARTICULATED_PARTS_METRIC_Y = 7,
        ARTICULATED_PARTS_METRIC_Y_RATE = 8,
        ARTICULATED_PARTS_METRIC_Z = 9,
        ARTICULATED_PARTS_METRIC_Z_RATE = 10,
        ARTICULATED_PARTS_METRIC_AZIMUTH = 11,
        ARTICULATED_PARTS_METRIC_AZIMUTH_RATE = 12,
        ARTICULATED_PARTS_METRIC_ELEVATION = 13,
        ARTICULATED_PARTS_METRIC_ELEVATION_RATE = 14,
        ARTICULATED_PARTS_METRIC_ROTATION = 15,
        ARTICULATED_PARTS_METRIC_ROTATION_RATE = 16,
        ARTICULATED_PARTS_METRIC_END
    } articulated_parts_metric_e;
}

#endif
