// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef BEAM_FUNCTION_H
#define BEAM_FUNCTION_H

namespace vdb
{
    typedef enum
    {
        BEAM_FUNCTION_BEAM_FUNC_OTHER = 0,
        BEAM_FUNCTION_BEAM_FUNC_SEARCH = 1,
        BEAM_FUNCTION_BEAM_FUNC_HEIGHT_FINDER = 2,
        BEAM_FUNCTION_BEAM_FUNC_ACQUISITION = 3,
        BEAM_FUNCTION_BEAM_FUNC_TRACKING = 4,
        BEAM_FUNCTION_BEAM_FUNC_ACQUISITION_AND_TRACKING = 5,
        BEAM_FUNCTION_BEAM_FUNC_COMMAND_GUIDANCE = 6,
        BEAM_FUNCTION_BEAM_FUNC_ILLUMINATION = 7,
        BEAM_FUNCTION_BEAM_FUNC_RANGE_ONLY_RADAR = 8,
        BEAM_FUNCTION_BEAM_FUNC_MISSILE_BEACON = 9,
        BEAM_FUNCTION_BEAM_FUNC_MISSILE_FUZE = 10,
        BEAM_FUNCTION_BEAM_FUNC_ACTIVE_RADAR_MISSILE_SEEKER = 11,
        BEAM_FUNCTION_BEAM_FUNC_JAMMER = 12,
        BEAM_FUNCTION_BEAM_FUNC_IFF = 13,
        BEAM_FUNCTION_BEAM_FUNC_NAVIGATIONAL_WEATHER = 14,
        BEAM_FUNCTION_BEAM_FUNC_METEOROLOGICAL = 15,
        BEAM_FUNCTION_BEAM_FUNC_DATA_TRANSMISSION = 16,
        BEAM_FUNCTION_BEAM_FUNC_NAVIGATIONAL_DIRECTIONAL_BEACON = 17,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_SEARCH = 20,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_ACQUISITION = 21,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_TRACK = 22,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_COMMAND_GUIDANCE = 23,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_ILLUMINATION = 24,
        BEAM_FUNCTION_BEAM_FUNC_TIME_SHARED_JAMMING = 25,
        BEAM_FUNCTION_END
    } beam_function_e;
}

#endif
