// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef EMITTER_FUNCTION_H
#define EMITTER_FUNCTION_H

namespace vdb
{
    typedef enum
    {
        EMITTER_FUNCTION_EMITTER_FUNC_OTHER = 0,
        EMITTER_FUNCTION_EMITTER_FUNC_MULTI_FUNCTION = 1,
        EMITTER_FUNCTION_EMITTER_FUNC_EARLY_WARNING_SURVEILLANCE = 2,
        EMITTER_FUNCTION_EMITTER_FUNC_HEIGHT_FINDER = 3,
        EMITTER_FUNCTION_EMITTER_FUNC_FIRE_CONTROL = 4,
        EMITTER_FUNCTION_EMITTER_FUNC_ACQUISITION_DETECTION = 5,
        EMITTER_FUNCTION_EMITTER_FUNC_TRACKER = 6,
        EMITTER_FUNCTION_EMITTER_FUNC_GUIDANCE_ILLUMINATION = 7,
        EMITTER_FUNCTION_EMITTER_FUNC_FIRING_POINT_LOCATION = 8,
        EMITTER_FUNCTION_EMITTER_FUNC_RANGE_ONLY = 9,
        EMITTER_FUNCTION_EMITTER_FUNC_RADAR_ALTIMETER = 10,
        EMITTER_FUNCTION_EMITTER_FUNC_IMAGING = 11,
        EMITTER_FUNCTION_EMITTER_FUNC_MOTION_DETECTION = 12,
        EMITTER_FUNCTION_EMITTER_FUNC_NAVIGATION = 13,
        EMITTER_FUNCTION_EMITTER_FUNC_WEATHER_METEROLOGICAL = 14,
        EMITTER_FUNCTION_EMITTER_FUNC_INSTRUMENTATION = 15,
        EMITTER_FUNCTION_EMITTER_FUNC_ID_CLASS = 16,
        EMITTER_FUNCTION_EMITTER_FUNC_AAA_FIRE_CONTROL = 17,
        EMITTER_FUNCTION_EMITTER_FUNC_AIR_SEARCH_BOMB = 18,
        EMITTER_FUNCTION_EMITTER_FUNC_AIR_INTERCEPT = 19,
        EMITTER_FUNCTION_EMITTER_FUNC_ALTIMETER = 20,
        EMITTER_FUNCTION_EMITTER_FUNC_AIR_MAPPING = 21,
        EMITTER_FUNCTION_EMITTER_FUNC_AIR_TRAFFIC_CONTROL = 22,
        EMITTER_FUNCTION_EMITTER_FUNC_BEACON = 23,
        EMITTER_FUNCTION_EMITTER_FUNC_BATTLEFIELD_SURVEILLANCE = 24,
        EMITTER_FUNCTION_EMITTER_FUNC_GROUND_CONTROL_APPROACH = 25,
        EMITTER_FUNCTION_EMITTER_FUNC_GROUND_CONTROL_INTERCEPT = 26,
        EMITTER_FUNCTION_EMITTER_FUNC_COASTAL_SURVEILLANCE = 27,
        EMITTER_FUNCTION_EMITTER_FUNC_DECOY_MIMIC = 28,
        EMITTER_FUNCTION_EMITTER_FUNC_DATA_TRANSMISSION = 29,
        EMITTER_FUNCTION_EMITTER_FUNC_EARTH_SURVEILLANCE = 30,
        EMITTER_FUNCTION_EMITTER_FUNC_GUN_LAY_BEACON = 31,
        EMITTER_FUNCTION_EMITTER_FUNC_GROUND_MAPPING = 32,
        EMITTER_FUNCTION_EMITTER_FUNC_HARBOR_SURVEILLANCE = 33,
        EMITTER_FUNCTION_EMITTER_FUNC_ILS = 35,
        EMITTER_FUNCTION_EMITTER_FUNC_IONOSPHERIC_SOUND = 36,
        EMITTER_FUNCTION_EMITTER_FUNC_INTERROGATOR = 37,
        EMITTER_FUNCTION_EMITTER_FUNC_BARRAGE_JAMMER = 38,
        EMITTER_FUNCTION_EMITTER_FUNC_CLICK_JAMMER = 39,
        EMITTER_FUNCTION_EMITTER_FUNC_FREQUENCY_SWEPT_JAMMER = 41,
        EMITTER_FUNCTION_EMITTER_FUNC_JAMMER = 42,
        EMITTER_FUNCTION_EMITTER_FUNC_PULSED_JAMMER = 44,
        EMITTER_FUNCTION_EMITTER_FUNC_REPEATER_JAMMER = 45,
        EMITTER_FUNCTION_EMITTER_FUNC_SPOT_NOISE_JAMMER = 46,
        EMITTER_FUNCTION_EMITTER_FUNC_MISSILE_ACQUISITION = 47,
        EMITTER_FUNCTION_EMITTER_FUNC_MISSILE_DOWNLINK = 48,
        EMITTER_FUNCTION_EMITTER_FUNC_SPACE = 50,
        EMITTER_FUNCTION_EMITTER_FUNC_SURFACE_SEARCH_ = 51,
        EMITTER_FUNCTION_EMITTER_FUNC_SHELL_TRACKING = 52,
        EMITTER_FUNCTION_EMITTER_FUNC_TELEVISION = 56,
        EMITTER_FUNCTION_EMITTER_FUNC_UNKNOWN = 57,
        EMITTER_FUNCTION_EMITTER_FUNC_VIDEO_REMOTING = 58,
        EMITTER_FUNCTION_EMITTER_FUNC_EXPERIMENTAL = 59,
        EMITTER_FUNCTION_EMITTER_FUNC_MISSILE_GUIDANCE = 60,
        EMITTER_FUNCTION_EMITTER_FUNC_MISSILE_HOMING = 61,
        EMITTER_FUNCTION_EMITTER_FUNC_MISSILE_TRACKING = 62,
        EMITTER_FUNCTION_EMITTER_FUNC_JAMMER_NOISE = 64,
        EMITTER_FUNCTION_EMITTER_FUNC_JAMMER_DECEPTION = 65,
        EMITTER_FUNCTION_EMITTER_FUNC_NAV_DIST_MEASURING_EQUIPMENT = 71,
        EMITTER_FUNCTION_EMITTER_FUNC_TERRAIN_FOLLOWING = 72,
        EMITTER_FUNCTION_EMITTER_FUNC_WEATHER_AVOIDANCE = 73,
        EMITTER_FUNCTION_EMITTER_FUNC_PROXIMITY_FUSE = 74,
        EMITTER_FUNCTION_EMITTER_FUNC_RADIOSONDE = 76,
        EMITTER_FUNCTION_EMITTER_FUNC_SONOBUOY = 77,
        EMITTER_FUNCTION_EMITTER_FUNC_BATHYTHERMAL_SENSOR = 78,
        EMITTER_FUNCTION_EMITTER_FUNC_TOWED_COUNTER_MEASURE = 79,
        EMITTER_FUNCTION_EMITTER_FUNC_WEAPON_NON_LETHAL = 96,
        EMITTER_FUNCTION_EMITTER_FUNC_WEAPON_LETHAL = 97,
        EMITTER_FUNCTION_END
    } emitter_function_e;
}

#endif
