// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef PHYS_CONN_TYPE_H
#define PHYS_CONN_TYPE_H

namespace vdb
{
    typedef enum
    {
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_NOT_SPECIFIED = 0,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_ATTACHED_TO_SURFACE = 1,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_CABLE_WIRE = 2,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_ROPE = 3,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_CHAIN = 4,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_POWER_LINE = 5,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_TELEPHONE_LINE = 6,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_CABLE_LINE = 7,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_REFUELING_DROGUE = 8,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_REFUELING_BOOM = 9,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_HANDCUFFS = 10,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_IN_CONTACT_WITH = 11,
        PHYS_CONN_TYPE_EAVP_PHYS_CONN_TYPE_FAST_ROPE = 12,
        PHYS_CONN_TYPE_END
    } phys_conn_type_e;
}

#endif
