// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef PHYS_ASSOC_TYPE_H
#define PHYS_ASSOC_TYPE_H

namespace vdb
{
    typedef enum
    {
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_NOT_SPECIFIED = 0,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR = 1,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_ON_LAND = 2,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_ON_WATER_SURFACE = 3,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_UNDERWATER = 4,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_MOUNTED_ATTACHED = 5,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_UNSUPP = 6,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_SUPP = 7,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_CENTER_HOOK = 8,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_FWD_HOOK = 9,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_AFT_HOOK = 10,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_TANDEM_HOOK = 11,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_FORE_CENTER = 12,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_CENTER_AFT = 13,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_ALL_HOOKS = 14,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_HOISTED = 15,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_LIFEFORM = 30,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_PLATFORM = 31,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_AN_OBJECT = 32,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_REFUELING_OPERATION = 61,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_SAR_BASKET = 62,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_SAR_RESCUE_COLLAR = 63,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_ENGAGEMENT = 64,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_RETURN_TO_BASE = 65,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_COMM_TOWERS = 90,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_POWER_TOWERS = 91,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_INDOORS = 92,
        PHYS_ASSOC_TYPE_EAVP_PHYS_ASSOC_TYPE_ROOF = 93,
        PHYS_ASSOC_TYPE_END
    } phys_assoc_type_e;
}

#endif
