// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef PRESENT_DOMAIN_H
#define PRESENT_DOMAIN_H

namespace vdb
{
    typedef enum
    {
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_UNCHANGED = 0,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_LAND = 1,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_AIR = 2,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SURFACE = 3,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBSURFACE = 4,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SPACE = 5,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBTERRANEAN_LAND = 6,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBTERRANEAN_AIR = 7,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBTERRANEAN_SURFACE = 8,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBTERRANEAN_SUBSURFACE = 9,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBSURFACE_TERRAIN = 10,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_SUBSURFACE_CAVES = 11,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_INTERIOR_OTHER_ENTITY = 12,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_EXTERIOR_OTHER_ENTITY = 13,
        PRESENT_DOMAIN_PRESENT_DOM_ENUM_ADMIN_INACTIVE = 14,
        PRESENT_DOMAIN_END
    } present_domain_e;
}

#endif
