// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef STATION_NAME_H
#define STATION_NAME_H

namespace vdb
{
    typedef enum
    {
        STATION_NAME_STATION_OTHER = 0,
        STATION_NAME_STATION_AIRCRAFT_WINGSTATION = 1,
        STATION_NAME_STATION_SHIPS_FORWARD_GUNMOUNT_STARBOARD = 2,
        STATION_NAME_STATION_SHIPS_FORWARD_GUNMOUNT_PORT = 3,
        STATION_NAME_STATION_SHIPS_FORWARD_GUNMOUNT_CENTERLINE = 4,
        STATION_NAME_STATION_SHIPS_AFT_GUNMOUNT_STARBOARD = 5,
        STATION_NAME_STATION_SHIPS_AFT_GUNMOUNT_PORT = 6,
        STATION_NAME_STATION_SHIPS_AFT_GUNMOUNT_CENTERLINE = 7,
        STATION_NAME_STATION_FORWARD_TORPEDO_TUBE = 8,
        STATION_NAME_STATION_AFT_TORPEDO_TUBE = 9,
        STATION_NAME_STATION_BOMB_BAY = 10,
        STATION_NAME_STATION_CARGO_BAY = 11,
        STATION_NAME_STATION_TRUCK_BED = 12,
        STATION_NAME_STATION_TRAILER_BED = 13,
        STATION_NAME_STATION_WELL_DECK = 14,
        STATION_NAME_STATION_ON_STATION_RNG_BRG = 15,
        STATION_NAME_STATION_ON_STATION_XYZ = 16,
        STATION_NAME_END
    } station_name_e;
}

#endif
