// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef WARHEAD_BURST_DESC_H
#define WARHEAD_BURST_DESC_H

namespace vdb
{
    typedef enum
    {
        WARHEAD_BURST_DESC_OTHER = 0,
        WARHEAD_BURST_DESC_CARGO = 10,
        WARHEAD_BURST_DESC_FUEL_AIR_EXPLOSIVE = 20,
        WARHEAD_BURST_DESC_GLASS_BEADS = 30,
        WARHEAD_BURST_DESC_1_UM = 31,
        WARHEAD_BURST_DESC_5_UM = 32,
        WARHEAD_BURST_DESC_10_UM = 33,
        WARHEAD_BURST_DESC_HIGH_EXPLOSIVE = 1000,
        WARHEAD_BURST_DESC_HE_PLASTIC = 1100,
        WARHEAD_BURST_DESC_HE_INCENDIARY = 1200,
        WARHEAD_BURST_DESC_HE_FRAGMENTATION = 1300,
        WARHEAD_BURST_DESC_HE_ANTITANK = 1400,
        WARHEAD_BURST_DESC_HE_BOMBLETS = 1500,
        WARHEAD_BURST_DESC_HE_SHAPED_CHARGE = 1600,
        WARHEAD_BURST_DESC_HE_CONTINUOUS_ROD = 1610,
        WARHEAD_BURST_DESC_HE_TUNGSTEN_BALL = 1615,
        WARHEAD_BURST_DESC_HE_BLAST_FRAGMENTATION = 1620,
        WARHEAD_BURST_DESC_HE_STEERABLE_DARTS_WITH_HE = 1625,
        WARHEAD_BURST_DESC_HE_DARTS = 1630,
        WARHEAD_BURST_DESC_HE_FLECHETTES = 1635,
        WARHEAD_BURST_DESC_HE_DIRECTED_FRAG = 1640,
        WARHEAD_BURST_DESC_HE_SEMI_ARMOR_PIERCING = 1645,
        WARHEAD_BURST_DESC_HE_SHAPED_CHARGE_FRAG = 1650,
        WARHEAD_BURST_DESC_HE_SEMI_ARMOR_PIERCING_FRAG = 1655,
        WARHEAD_BURST_DESC_HE_HOLLOW_CHARGE = 1660,
        WARHEAD_BURST_DESC_HE_DOUBLE_HOLLOW_CHARGE = 1665,
        WARHEAD_BURST_DESC_HE_GENERAL_PURPOSE = 1670,
        WARHEAD_BURST_DESC_HE_BLAST_PENETRATOR = 1675,
        WARHEAD_BURST_DESC_HE_ROD_PENETRATOR = 1680,
        WARHEAD_BURST_DESC_HE_ANTIPERSONNEL = 1685,
        WARHEAD_BURST_DESC_SMOKE = 2000,
        WARHEAD_BURST_DESC_ILLUMINATION = 3000,
        WARHEAD_BURST_DESC_PRACTICE = 4000,
        WARHEAD_BURST_DESC_KINETIC = 5000,
        WARHEAD_BURST_DESC_MINES = 6000,
        WARHEAD_BURST_DESC_NUCLEAR = 7000,
        WARHEAD_BURST_DESC_NUCLEAR_IMT = 7010,
        WARHEAD_BURST_DESC_CHEMICAL_GENERAL = 8000,
        WARHEAD_BURST_DESC_CHEMICAL_BLISTER_AGENT = 8100,
        WARHEAD_BURST_DESC_HD_MUSTARD = 8110,
        WARHEAD_BURST_DESC_THICKENED_HD_MUSTARD = 8115,
        WARHEAD_BURST_DESC_DUSTY_HD_MUSTARD = 8120,
        WARHEAD_BURST_DESC_CHEMICAL_BLOOD_AGENT = 8200,
        WARHEAD_BURST_DESC_AC_HCN = 8210,
        WARHEAD_BURST_DESC_CK_CNCI = 8215,
        WARHEAD_BURST_DESC_CG_PHOSGENE = 8220,
        WARHEAD_BURST_DESC_CHEMICAL_NERVE_AGENT = 8300,
        WARHEAD_BURST_DESC_VX = 8310,
        WARHEAD_BURST_DESC_THICKENED_VX = 8315,
        WARHEAD_BURST_DESC_DUSTY_VX = 8320,
        WARHEAD_BURST_DESC_GA_TABUN = 8325,
        WARHEAD_BURST_DESC_THICKENED_GA_TABUN = 8330,
        WARHEAD_BURST_DESC_DUSTY_GA_TABUN = 8335,
        WARHEAD_BURST_DESC_GB_SARIN = 8340,
        WARHEAD_BURST_DESC_THICKENED_GB_SARIN = 8345,
        WARHEAD_BURST_DESC_DUSTY_GB_SARIN = 8350,
        WARHEAD_BURST_DESC_GD_SOMAN = 8355,
        WARHEAD_BURST_DESC_THICKENED_GD_SOMAN = 8360,
        WARHEAD_BURST_DESC_DUSTY_GD_SOMAN = 8365,
        WARHEAD_BURST_DESC_GF = 8370,
        WARHEAD_BURST_DESC_THICKENED_GF = 8375,
        WARHEAD_BURST_DESC_DUSTY_GF = 8380,
        WARHEAD_BURST_DESC_BIOLOGICAL = 9000,
        WARHEAD_BURST_DESC_BIOLOGICAL_VIRUS = 9100,
        WARHEAD_BURST_DESC_BIOLOGICAL_BACTERIA = 9200,
        WARHEAD_BURST_DESC_BIOLOGICAL_RICKETTSIA = 9300,
        WARHEAD_BURST_DESC_BIOGEN_MOD_MICRO_ORGANISMS = 9400,
        WARHEAD_BURST_DESC_BIOLOGICAL_TOXIN = 9500,
        WARHEAD_BURST_DESC_END
    } warhead_burst_desc_e;
}

#endif
