// -----------------------------------------------
// This file is script-generated...
// -----------------------------------------------

#ifndef WS_HAZE_TYPE_H
#define WS_HAZE_TYPE_H

namespace vdb
{
    typedef enum
    {
        WS_HAZE_TYPE_WSH_TYPE_NO_HAZE = 0,
        WS_HAZE_TYPE_WSH_TYPE_OTHER_HAZE = 1,
        WS_HAZE_TYPE_WSH_TYPE_RURUAL_HAZE = 2,
        WS_HAZE_TYPE_WSH_TYPE_MARITIME_HAZE = 3,
        WS_HAZE_TYPE_WSH_TYPE_URBAN_HAZE = 4,
        WS_HAZE_TYPE_WSH_TYPE_TROPOSPHERIC_HAZE = 5,
        WS_HAZE_TYPE_WSH_TYPE_ADVECTIVE_FOG_HAZE = 6,
        WS_HAZE_TYPE_WSH_TYPE_RADIATIVE_FOG_HAZE = 7,
        WS_HAZE_TYPE_WSH_TYPE_DESERT_HAZE = 8,
        WS_HAZE_TYPE_WSH_TYPE_DESERT_SUMMER_HAZE = 9,
        WS_HAZE_TYPE_WSH_TYPE_DESERT_WINTER_HAZE = 10,
        WS_HAZE_TYPE_WSH_TYPE_TEMPERATE_SUMMER_DAY = 11,
        WS_HAZE_TYPE_WSH_TYPE_TEMPERATE_SUMMER_NIGHT = 12,
        WS_HAZE_TYPE_WSH_TYPE_TEMPERATE_WINTER = 13,
        WS_HAZE_TYPE_WSH_TYPE_DUST_STORM_HAZE = 14,
        WS_HAZE_TYPE_WSH_TYPE_SNOW_HAZE_ = 15,
        WS_HAZE_TYPE_WSH_TYPE_BLOWING_SNOW_HAZE = 16,
        WS_HAZE_TYPE_WSH_TYPE_FOG_AND_SNOW_HAZE = 17,
        WS_HAZE_TYPE_END
    } ws_haze_type_e;
}

#endif
